In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Manipulating tensors

In [2]:
tensor = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [3]:
tensor+10

tensor([[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])

In [4]:
tensor*10

tensor([[10., 20., 30.],
        [40., 50., 60.],
        [70., 80., 90.]])

In [5]:
tensor/10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [6]:
tensor**2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [7]:
tensor*tensor

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [10]:
tensor.matmul(tensor)

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [11]:
torch.matmul(tensor, tensor)

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [13]:
%%time
tensor @ tensor

CPU times: user 125 µs, sys: 56 µs, total: 181 µs
Wall time: 186 µs


tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

### Matrix multiplication

In [17]:
%%time
random_tensor_A = torch.rand((3,5))
random_tensor_B = torch.rand((5
                            ,10))

random_tensor_A @ random_tensor_B

CPU times: user 444 µs, sys: 394 µs, total: 838 µs
Wall time: 594 µs


tensor([[0.5294, 0.7423, 0.9162, 1.1668, 0.9324, 0.6559, 0.7332, 0.2565, 0.9264,
         0.5406],
        [0.7877, 0.6336, 0.5096, 1.1435, 1.3228, 0.9876, 0.6898, 0.9510, 1.2402,
         0.3864],
        [1.0837, 1.0087, 1.4202, 1.6839, 1.5546, 0.8046, 1.5387, 0.4339, 1.4754,
         0.9518]])

In [19]:
random_tensor_A.T, random_tensor_B.shape

(tensor([[0.0999, 0.0920, 0.7239],
         [0.5780, 0.1182, 0.8329],
         [0.1144, 0.6341, 0.7954],
         [0.5299, 0.2438, 0.2047],
         [0.0713, 0.8092, 0.0558]]),
 torch.Size([5, 10]))

## tensor aggregation

In [20]:
tensor_x = torch.arange(0,10,0.5)
tensor_x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [22]:
tensor_x.min()

tensor(0.)

In [23]:
tensor_x.max()

tensor(9.5000)

In [24]:
tensor_x.mean()

tensor(4.7500)

In [25]:
tensor_x.std(), tensor_x.var(), tensor_x.median(), tensor_x.sum()

(tensor(2.9580), tensor(8.7500), tensor(4.5000), tensor(95.))

### Finding the positional mean 

In [26]:
tensor_x.argmin(), tensor_x.argmax()

(tensor(0), tensor(19))

In [27]:
torch.argmin(tensor_x), torch.argmax(tensor_x)

(tensor(0), tensor(19))

In [28]:
tensor_x[19]

tensor(9.5000)

In [29]:
tensor_x[19].item()

9.5

In [30]:
torch.argmin(tensor_x).item()

0

## Reshaping tensors

In [31]:
random_tensor_A = torch.rand((3,5))
random_tensor_A

tensor([[0.8060, 0.2675, 0.4040, 0.4907, 0.5171],
        [0.5923, 0.3164, 0.1424, 0.6331, 0.5535],
        [0.7972, 0.6308, 0.4881, 0.7356, 0.4484]])

In [39]:
random_tensor_B = random_tensor_A.reshape((5,3))

In [40]:
random_tensor_A.reshape((5,3)).shape

torch.Size([5, 3])

In [41]:
z = random_tensor_A.view(15,1)
z, z.shape

(tensor([[0.8060],
         [0.2675],
         [0.4040],
         [0.4907],
         [0.5171],
         [0.5923],
         [0.3164],
         [0.1424],
         [0.6331],
         [0.5535],
         [0.7972],
         [0.6308],
         [0.4881],
         [0.7356],
         [0.4484]]),
 torch.Size([15, 1]))

In [42]:
torch.stack((z,z,z), dim=1)

tensor([[[0.8060],
         [0.8060],
         [0.8060]],

        [[0.2675],
         [0.2675],
         [0.2675]],

        [[0.4040],
         [0.4040],
         [0.4040]],

        [[0.4907],
         [0.4907],
         [0.4907]],

        [[0.5171],
         [0.5171],
         [0.5171]],

        [[0.5923],
         [0.5923],
         [0.5923]],

        [[0.3164],
         [0.3164],
         [0.3164]],

        [[0.1424],
         [0.1424],
         [0.1424]],

        [[0.6331],
         [0.6331],
         [0.6331]],

        [[0.5535],
         [0.5535],
         [0.5535]],

        [[0.7972],
         [0.7972],
         [0.7972]],

        [[0.6308],
         [0.6308],
         [0.6308]],

        [[0.4881],
         [0.4881],
         [0.4881]],

        [[0.7356],
         [0.7356],
         [0.7356]],

        [[0.4484],
         [0.4484],
         [0.4484]]])

In [43]:
torch_zeroes = torch.zeros((3,5))
torch_zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [44]:
# squeeze
torch_zeroes.squeeze()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [46]:
torch_zeroes.reshape((1,3,5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [47]:
torch_zeroes.squeeze()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [48]:
torch_zeroes.unsqueeze(dim=0)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [49]:
torch_zeroes.unsqueeze(dim=1)

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [57]:
new_x =torch_zeroes.unsqueeze(dim=1)
new_x

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [58]:

new_x.shape

torch.Size([3, 1, 5])

In [59]:
torch_zeroes.permute(1,0)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [60]:
torch_zeroes.permute(1,0).shape

torch.Size([5, 3])

In [61]:
torch_zeroes.permute(1,0).unsqueeze(dim=0)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [62]:
torch_zeroes.permute(1,0).unsqueeze(dim=0).shape

torch.Size([1, 5, 3])

In [63]:
x_original = torch.rand(size=(224,224,3))
x_permute = x_original.permute(2,0,1)
x_permute.shape, x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [64]:
x_original[0,0,0] = 100
x_original[0,0,0], x_permute[0,0,0]

(tensor(100.), tensor(100.))

In [65]:
x_original[0,0,0] = 0
x_original[0,0,0], x_permute[0,0,0]

(tensor(0.), tensor(0.))

### Indexing and slicing tensors

In [68]:
new_tensor = torch.arange(0,9).reshape(1,3,3)

In [69]:
new_tensor

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

In [71]:
new_tensor[0,1]

tensor([3, 4, 5])

In [73]:
new_tensor[:,1,1]

tensor([4])

In [75]:
new_tensor[0,1]

tensor([3, 4, 5])

In [82]:
new_tensor[:,2,2]

tensor([8])

# Numpy and pytorch

In [85]:
np_array = np.arange(0,9).reshape(3,3)
torch_np_array = torch.from_numpy(np_array).type(torch.float32)
torch_np_array, np_array, torch_np_array.dtype

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 torch.float32)

In [87]:
tensor_ones = torch.ones((3,3), dtype=torch.int32)
numpy_ones = tensor_ones.numpy()
tensor_ones, numpy_ones, numpy_ones.dtype

(tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]], dtype=torch.int32),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int32),
 dtype('int32'))

In [88]:
tensor+1

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])

In [89]:
tensor_ones+1

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

## PyTorch reproducibility

In [90]:
random_tensor_A = torch.rand((3,5))
random_tensor_B = torch.rand((3,5))
random_tensor_A == random_tensor_B

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [93]:
# flavour out the random number 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand((3,5))
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand((3,5))
random_tensor_A == random_tensor_B

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

## GPU acceleration

In [96]:
torch.cuda.is_available()

False

In [97]:
## enable gpu for mac
device = "cuda" if torch.cuda.is_available() else "cpu"

In [103]:
# count the number of devices
torch.cuda.device_count()

0