In [15]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

In [16]:
scalar = torch.tensor(3.1415)
scalar

tensor(3.1415)

In [17]:
scalar.ndim

0

In [18]:
scalar.item()

3.1414999961853027

In [19]:
# vector
vector = torch.tensor([1,2,3,4])

In [20]:
vector.ndim

1

In [21]:
vector.shape

torch.Size([4])

In [22]:
# matrix
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [23]:
matrix.ndim

2

In [24]:
matrix.shape

torch.Size([2, 3])

In [25]:
# tensor
tensor = torch.tensor([[[1,2,3],[2,3,4]]])

In [26]:
tensor.ndim

3

In [27]:
tensor.shape

torch.Size([1, 2, 3])

In [28]:
tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4]])

## Random tensor
Random tensor is a tensor of a given shape, with random values for each element. The random values are sampled from a uniform distribution between 0 and 1.

In [31]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0081, 0.9557, 0.3072, 0.5228],
        [0.6835, 0.8320, 0.7028, 0.3200],
        [0.2347, 0.7747, 0.3444, 0.3691]])

In [32]:
random_tensor.ndim

2

In [33]:
random_tensor.shape

torch.Size([3, 4])

In [34]:
# Random tensor with normal distribution
random_tensor_normal = torch.randn(3,4)

In [35]:
random_tensor_normal

tensor([[ 0.5713,  0.6960,  0.7088,  0.5687],
        [ 0.0156, -0.3715,  0.0038,  1.4512],
        [-1.3432,  0.6297, -0.6081,  1.7810]])

In [36]:
random_tensor_normal.ndim

2

In [37]:
random_tensor_normal.shape

torch.Size([3, 4])

In [38]:
# Random tensor with random integers
random_tensor_int = torch.rand(10,10,10)

In [39]:
random_tensor_int

tensor([[[9.3211e-01, 5.1291e-01, 1.4105e-01, 1.4228e-01, 8.8574e-01,
          9.0893e-01, 6.8696e-01, 4.6923e-02, 5.9236e-01, 9.3951e-01],
         [9.7974e-01, 2.2136e-01, 6.5436e-01, 7.5877e-01, 6.8815e-01,
          8.4403e-01, 3.9651e-01, 6.5029e-01, 3.1179e-01, 3.2685e-01],
         [7.6825e-01, 3.8603e-01, 8.7334e-01, 9.4379e-01, 4.3355e-01,
          2.7609e-02, 3.4250e-02, 2.3261e-02, 1.6394e-01, 8.4953e-01],
         [7.8555e-01, 1.6767e-01, 6.2939e-01, 1.4109e-01, 4.4775e-01,
          2.2445e-01, 3.3929e-01, 6.0636e-01, 4.8517e-01, 4.8106e-01],
         [6.4063e-01, 3.0498e-01, 5.4112e-01, 9.8147e-01, 8.0643e-01,
          8.1873e-01, 1.2150e-01, 2.3693e-01, 4.2671e-01, 3.4638e-01],
         [5.5221e-01, 6.0480e-01, 5.0331e-01, 4.6776e-01, 3.5203e-01,
          1.1410e-01, 5.8979e-01, 9.9660e-01, 9.0981e-01, 5.6979e-01],
         [5.4461e-01, 4.3125e-01, 6.5529e-01, 2.5702e-02, 4.4990e-01,
          8.7869e-01, 1.9171e-01, 2.2759e-02, 7.2289e-01, 5.5370e-01],
         [3.8

## Create random tensor similar to an image

In [40]:
random_tensor_image = torch.rand(size=(1,3,256,256))
random_tensor_image, random_tensor_image.shape, random_tensor_image.ndim

(tensor([[[[0.2756, 0.8000, 0.6022,  ..., 0.5759, 0.3052, 0.1862],
           [0.6697, 0.7100, 0.2909,  ..., 0.5587, 0.1104, 0.5834],
           [0.0909, 0.2940, 0.2181,  ..., 0.0159, 0.7651, 0.3039],
           ...,
           [0.6799, 0.3458, 0.7324,  ..., 0.4782, 0.1967, 0.9023],
           [0.1688, 0.4463, 0.0404,  ..., 0.8710, 0.4553, 0.5830],
           [0.2542, 0.4831, 0.0326,  ..., 0.2696, 0.5207, 0.4058]],
 
          [[0.8669, 0.7025, 0.8599,  ..., 0.8928, 0.0508, 0.0066],
           [0.4684, 0.8841, 0.5836,  ..., 0.2761, 0.2332, 0.0697],
           [0.0729, 0.2064, 0.4191,  ..., 0.4015, 0.7749, 0.3603],
           ...,
           [0.5994, 0.3692, 0.7343,  ..., 0.1362, 0.6442, 0.9645],
           [0.5530, 0.5307, 0.5983,  ..., 0.1065, 0.1049, 0.8715],
           [0.7066, 0.1551, 0.8974,  ..., 0.0343, 0.5337, 0.6558]],
 
          [[0.9471, 0.7988, 0.8509,  ..., 0.0135, 0.9217, 0.9153],
           [0.0063, 0.2136, 0.1118,  ..., 0.5427, 0.6810, 0.9721],
           [0.8021, 0.90

### Zeroes and ones tensor

In [42]:
zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a tensor in a range   

In [45]:
ones_to_20 = torch.arange(1,21)
ones_to_20

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [49]:
twenty_zeroes = torch.zeros_like(ones_to_20)
twenty_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
h