In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors

In [2]:
scalar = torch.tensor(3.1415)
scalar

tensor(3.1415)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

3.1414999961853027

In [5]:
# vector
vector = torch.tensor([1,2,3,4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([4])

In [8]:
# matrix
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 3])

In [11]:
# tensor
tensor = torch.tensor([[[1,2,3],[2,3,4]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 2, 3])

In [14]:
tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4]])

## Random tensor
Random tensor is a tensor of a given shape, with random values for each element. The random values are sampled from a uniform distribution between 0 and 1.

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2945, 0.5487, 0.7120, 0.9045],
        [0.2531, 0.1728, 0.1203, 0.4021],
        [0.8717, 0.6537, 0.9715, 0.6302]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([3, 4])

In [18]:
# Random tensor with normal distribution
random_tensor_normal = torch.randn(3,4)

In [19]:
random_tensor_normal

tensor([[-0.7084,  1.1721,  0.9090,  0.9883],
        [ 0.1939,  0.4397,  2.3501, -0.1885],
        [-1.3553,  1.3604,  0.4559, -1.1192]])

In [20]:
random_tensor_normal.ndim

2

In [21]:
random_tensor_normal.shape

torch.Size([3, 4])

In [22]:
# Random tensor with random integers
random_tensor_int = torch.rand(10,10,10)

In [23]:
random_tensor_int

tensor([[[2.4418e-01, 5.5138e-01, 1.7627e-02, 1.3469e-02, 6.2997e-01,
          7.4950e-01, 1.8162e-01, 4.9051e-01, 5.6989e-01, 6.4674e-01],
         [3.2873e-01, 7.7813e-01, 5.8773e-01, 7.0842e-01, 1.8979e-01,
          5.1142e-01, 7.2492e-01, 4.5433e-01, 6.1527e-02, 4.1028e-01],
         [8.4375e-02, 7.9425e-02, 7.8994e-01, 9.5383e-01, 7.6816e-01,
          7.8015e-01, 6.4693e-01, 2.8548e-01, 9.8630e-01, 2.9393e-01],
         [4.6165e-01, 9.5853e-01, 3.0024e-01, 1.9024e-02, 4.7821e-01,
          1.8909e-01, 9.6905e-01, 5.7074e-01, 5.3386e-01, 9.2303e-01],
         [1.4408e-01, 1.7812e-01, 3.6697e-01, 8.6096e-01, 5.8873e-02,
          6.1390e-01, 1.7748e-01, 6.6473e-01, 3.0024e-01, 1.5665e-01],
         [8.2962e-01, 2.5879e-01, 1.0925e-01, 8.3650e-01, 3.1173e-01,
          5.6130e-01, 9.6729e-01, 7.7946e-01, 5.6999e-01, 7.9438e-01],
         [5.9165e-01, 3.7889e-01, 6.2826e-02, 5.5481e-01, 1.6181e-01,
          2.7859e-01, 8.4569e-01, 4.0708e-03, 7.2775e-01, 9.2161e-02],
         [2.5

## Create random tensor similar to an image

In [24]:
random_tensor_image = torch.rand(size=(1,3,256,256))
random_tensor_image, random_tensor_image.shape, random_tensor_image.ndim

(tensor([[[[7.7548e-01, 3.0572e-01, 9.6353e-01,  ..., 4.9223e-01,
            1.6636e-02, 1.2299e-01],
           [8.1192e-01, 2.7240e-01, 6.6812e-01,  ..., 9.2803e-01,
            5.1119e-01, 4.1617e-01],
           [3.0269e-01, 1.0459e-01, 2.3262e-02,  ..., 6.1549e-01,
            5.3623e-01, 3.9629e-01],
           ...,
           [3.9749e-01, 7.1658e-01, 8.5475e-01,  ..., 2.6933e-01,
            2.9936e-01, 9.6109e-01],
           [1.4400e-01, 7.2550e-01, 7.5643e-01,  ..., 8.3170e-01,
            7.5891e-01, 4.5649e-01],
           [9.3557e-01, 9.3814e-01, 2.8101e-01,  ..., 7.8093e-01,
            8.0318e-01, 9.9214e-01]],
 
          [[5.2876e-03, 6.1626e-01, 9.0689e-01,  ..., 3.1452e-01,
            7.7092e-01, 7.9160e-01],
           [5.1202e-01, 5.6116e-01, 9.9281e-01,  ..., 2.4352e-01,
            3.1459e-01, 7.9209e-01],
           [2.3176e-01, 5.2927e-01, 6.6490e-02,  ..., 7.2510e-01,
            1.8003e-01, 3.2409e-01],
           ...,
           [7.9379e-01, 1.2353e-01, 4.

### Zeroes and ones tensor

In [25]:
zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a tensor in a range   

In [27]:
ones_to_20 = torch.arange(1,21)
ones_to_20

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [28]:
twenty_zeroes = torch.zeros_like(ones_to_20)
twenty_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
float_32_tensor = torch.tensor([1.0,2.0,4.0], 
                             dtype=None,
                             device=None,
                             requires_grad=False)

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 4.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 1.,  4., 16.])

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
int_32_tensor*float_32_tensor

tensor([ 3., 12., 36.])

In [40]:
int_32_tensor.device

device(type='cpu')

In [41]:
some_tensor = torch.rand(4,5)
some_tensor

tensor([[0.1959, 0.2715, 0.4388, 0.7881, 0.3731],
        [0.1950, 0.9830, 0.3844, 0.0269, 0.7879],
        [0.6271, 0.3018, 0.8666, 0.9224, 0.7626],
        [0.9874, 0.8346, 0.2505, 0.9391, 0.8168]])

In [42]:
# info about the tensor
print("Data type: ", some_tensor.dtype)
print("Device tensor is stored on: ", some_tensor.device)
print("Shape of tensor: ", some_tensor.shape)

Data type:  torch.float32
Device tensor is stored on:  cpu
Shape of tensor:  torch.Size([4, 5])


In [43]:
# move tensor to GPU if available
if torch.cuda.is_available():
    some_tensor = some_tensor.to('cuda')
    print("Device tensor is stored on: ", some_tensor.device)

In [44]:
some_tensor.device

device(type='cpu')

### Manipulating tensors